export enum CatsActionTypes {
  GET_CATS = "GET_CATS",
  GET_CATEGORIES = "GET_CATEGORIES",
  LOADING_CATS = "LOADING_CATS",
  GET_ACTIVE_CATEGORY = "GET_ACTIVE_CATEGORY",
  GET_ACTIVE_PAGE = "GET_ACTIVE_PAGE"
}
